Add triggers cli
HCK-CI/AutoHCK pull request #192
Opened 2023-02-24 10:55 UTC by kostyanf14

2023-02-25 04:17 UTC, akihikodaki requested changes

2023-02-25 04:17 UTC, akihikodaki commented on spec/diff_checker_spec.rb
> +    drivers_name = [name_parts[2] ]
```suggestion
    drivers_name = [name_parts[2]]
```

2023-02-27 08:30 UTC, kostyanf14 commented on spec/diff_checker_spec.rb
> +    drivers_name = [name_parts[2] ]
Fixed

2023-02-27 08:31 UTC, akihikodaki approved these changes

2023-02-27 08:51 UTC, merged