Run pre start command before each QEMU run
HCK-CI/AutoHCK pull request #249
Opened 2023-09-14 17:02 UTC by kostyanf14

When QEMU exits, device daemons exit too, so we should run it again before start QEMU.

2023-09-18 11:19 UTC, akihikodaki requested changes
This doesn't look correct. In the case of `ivshmem-doorbell`, the ivshmem server terminates during the execution of `post_stop_commands`, which only happens after `@qemu_thread` terminates. Repetitively running `pre_start_commands` will result in multiple ivshmem server processes running.

What daemons automatically quit after QEMU exits?

2023-09-18 11:42 UTC, kostyanf14 commented
>What daemons automatically quit after QEMU exits?

virtiofsd and swtpm

2023-09-18 12:06 UTC, akihikodaki requested changes
Let's move `@machine.run_post_stop_commands` into `@qemu_thread` then.

2023-09-18 14:20 UTC, akihikodaki requested changes
`ensure` clause must be used so that `post_stop_commands` will be always executed.

2023-09-19 02:03 UTC, akihikodaki requested changes

2023-09-19 02:03 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +            @machine.run_pre_start_commands
`@machine.run_pre_start_commands` should be in `Thread.handle_interrupt(Object => :on_blocking)` block. There is a possibility that `@machine.run_pre_start_commands` did some work that must be discarded with `              @machine.run_post_stop_commands` before raising an exception.

2023-09-19 06:29 UTC, akihikodaki approved these changes

2023-09-19 07:17 UTC, YanVugenfirer approved these changes

2023-09-19 07:17 UTC, merged