AutoHCK fail when rerun test with BSOD
HCK-CI/AutoHCK pull request #303
Opened 2024-02-15 17:22 UTC by Jedoku

2024-02-15 17:26 UTC, kostyanf14 requested changes

2024-02-15 17:26 UTC, kostyanf14 commented on lib/engines/hcktest/tests.rb
>        collected_support = collect_memory_dump(@support.name, "#{l_tmp_path}/#{@support.name}") unless @support.nil?
Both clients can generate BSOD. So add timestamp for support VM too

2024-02-17 08:12 UTC, akihikodaki requested changes
Can you have an explanation for me, who doesn't know the context? For me, it looks immune against collisions even without a timestamp since the zip has the id.

Why did you use id instead of timestamp? It's inconsistent.
If you really need timestsamps, extract `AutoHCK::Project#create_timestamp` into a helper and change this to use it.

2024-02-17 13:07 UTC, Jedoku commented
> Can you have an explanation for me, who doesn't know the context? For me, it looks immune against collisions even without a timestamp since the zip has the id.
> 
> Why did you use id instead of timestamp? It's inconsistent. If you really need timestsamps, extract `AutoHCK::Project#create_timestamp` into a helper and change this to use it.

When we start a test with a dump twice, we have to save both dumps into a zip archive. The problem arises when we save a folder with the name of the client's VM (CL01 in this case) into the zip file. When we try to add the folder a second time, we receive an error stating that the folder already exists. The solution to this issue involves adding a timestamp to the folder name, allowing us to circumvent the problem.

2024-02-17 13:22 UTC, akihikodaki commented
@Jedoku I see. Thanks for the explanation.

2024-02-20 05:12 UTC, akihikodaki requested changes

2024-02-20 05:12 UTC, akihikodaki commented on lib/auxiliary/time_helper.rb
>      def timestamp
Naming this timestamp will collide with `Project#timestamp` attr_reader so it's better to avoid.

2024-02-21 16:04 UTC, kostyanf14 requested changes

2024-02-21 16:04 UTC, kostyanf14 commented on lib/auxiliary/time_helper.rb
> +    def add_timestamp
This function does not add a timestamp it gets a timestamp. As `get_timestamp` is a bad name from a Ruby point of view, use `create_timestamp`, `generate_timestamp`, `current_timestamp`, etc

2024-02-21 16:46 UTC, kostyanf14 approved these changes

2024-02-22 06:00 UTC, akihikodaki requested changes

2024-02-22 06:00 UTC, akihikodaki commented on lib/engines/hcktest/tests.rb
> +      collected_client = download_memory_dump(@client.name, "#{l_tmp_path}/#{@client.name}_#{current_timestamp}")
We only download dumps here; please rename `collected_client` to `downloaded_client`. Do the same for `collected_support` too.

2024-02-23 08:38 UTC, akihikodaki approved these changes

2024-02-25 07:33 UTC, merged