Initialize partition for viostor/vioblk testing
HCK-CI/AutoHCK pull request #374
Opened 2024-05-28 15:19 UTC by kostyanf14

Initialize-Disk for some reason creates a small partition, so we must remove it before creating a new one. This behavior was tested on Server 2016/2022/2025.

2024-05-29 06:53 UTC, akihikodaki requested changes

2024-05-29 06:53 UTC, akihikodaki commented on lib/engines/hcktest/drivers/vioscsi.json
> +      "run": "Get-Partition -DiskNumber 1 | Remove-Partition -Confirm:$false"
It looks like `Remove-Partition` can directly take `-DiskNumber` and `-PartitionNumber`. It's already supported by Windows 2012: https://learn.microsoft.com/en-us/powershell/module/storage/remove-partition?view=winserver2012-ps

2024-06-02 05:12 UTC, akihikodaki approved these changes

2024-06-02 21:48 UTC, Jedoku approved these changes

2024-06-04 07:21 UTC, merged