Add ability to specify per test special config
HCK-CI/AutoHCK pull request #463
Opened 2024-09-07 23:10 UTC by Jedoku

2024-09-08 06:55 UTC, akihikodaki requested changes

2024-09-08 06:55 UTC, akihikodaki commented on lib/models/hcktest_config.rb
> +      const :test_parameters, T.nilable(T::Array[TestParameter])
I guess you should specify `default: []` instead of making it nilable. `Tests#test_parameters` will raise an error if this is `nil`.

2024-09-08 10:10 UTC, YanVugenfirer commented on svvp.json
> -    "USB Type-C ACPI Validation",
I think it is worth separation changes like this to separate commit.

2024-09-09 08:01 UTC, Jedoku commented on lib/engines/hcktest/tools.rb
> +    def queue_test(**test_params)
Metrics/ParameterLists: Avoid parameter lists longer than 5 parameters. [6/5]

2024-09-09 08:12 UTC, akihikodaki commented on lib/engines/hcktest/tools.rb
> +    def queue_test(**test_params)
Please explicitly disable the rule instead of degrading the code quality to workaround it.

2024-09-10 04:12 UTC, akihikodaki requested changes
Please merge `tests_config` and `test_parameters`. They both describe tests and we can reduce redundancy of e.g., `TestConfig` and `TestParameter` classes.

2024-09-13 03:50 UTC, akihikodaki approved these changes

2024-09-16 07:19 UTC, kostyanf14 approved these changes

2024-09-16 07:19 UTC, merged