RFC: Flush stor
HCK-CI/AutoHCK pull request #486
Opened 2024-10-03 17:17 UTC by kostyanf14

2024-10-04 04:12 UTC, akihikodaki requested changes

2024-10-04 04:12 UTC, akihikodaki commented on bin/fake-snmp-reset
> +end
I prefer having stateless methods instead of having a class with full of states. Especially we can connect QMP each time to make the code simpler.

2024-10-04 04:12 UTC, akihikodaki commented on bin/fake-snmp-reset
> +      raise response['error'].to_s if response.key?('error')
Use `@logger.error` and break to keep the server alive in case of error.

2024-10-04 04:12 UTC, akihikodaki commented on bin/fake-snmp-reset
> +log.level = Logger::DEBUG
This is unnecessary; `DEBUG` is the default log level.

2024-10-04 04:12 UTC, akihikodaki commented on bin/fake-snmp-reset
> +log.info "START #{ARGV}"
Let's remove this; I don't see a point of failure between this log and "Initializing UDP socket".

2024-10-04 04:12 UTC, akihikodaki commented on bin/ns_unshared
> +      # need for access to host without full Internet access
nit:

```suggestion
      # needed for access to host without full Internet access
```

2024-10-05 04:25 UTC, akihikodaki approved these changes

2024-10-06 13:18 UTC, YanVugenfirer approved these changes

2024-10-10 08:20 UTC, akihikodaki requested changes
https://oidref.com/1.3.6.1.4.1.318.1.1.12.3.3.1.1.4 says it has `delayedReboot` so you may check if the value is used. I don't require to do so as Microsoft's documentation does not mention it.

2024-10-10 08:20 UTC, akihikodaki commented on bin/fake-snmp-reset
> +  UDPSocket.open do |socket|
I think you can put `UDPSocket.open` before the loop now.

2024-10-10 08:29 UTC, akihikodaki commented on bin/fake-snmp-reset
> +    _, addr = socket.recvfrom(512)
To discard all data:

```suggestion
    _, addr = socket.recvfrom(0)
```

2024-10-12 06:39 UTC, akihikodaki approved these changes

2024-10-13 10:14 UTC, YanVugenfirer approved these changes

2024-10-13 10:15 UTC, merged

2025-02-26 12:03 UTC, benyamin-codez commented
@kostyanf14

Thanks for the reference.

I noticed the [MS doco](https://learn.microsoft.com/en-us/windows-hardware/test/hlk/testref/2dec1f67-b506-4434-8bdf-763147ad8f0b#power-strip) suggested the following ASNs are required:

* ImmediatePowerOn = 1
* ImmediatePowerOff = 2
* ImmediateReboot = 3

_[sic] - I'm presuming typographic errors here, and these should actually be:_

* immediateOn = 1
* immediateOff = 2
* immediateReboot = 3

...from https://oidref.com/1.3.6.1.4.1.318.1.1.12.3.3.1.1.4 (the relevant OID):

```
rPDUOutletControlOutletCommand OBJECT-TYPE
   SYNTAX INTEGER {
      immediateOn             (1),
      immediateOff            (2),
      immediateReboot         (3),
      delayedOn               (4),
      delayedOff              (5),
      delayedReboot           (6),
      cancelPendingCommand    (7)
   }
```

As the first two, i.e. _immediateOn_ and _immediateOff_, are `read-write`, i.e. `set/get`, perhaps we are performing the `system-reset` via QMP, not only when the test issues the command but perhaps also when the test issues a query to check the power state.

***So when asked to check the power state, perhaps we are resetting instead...*** 8^O

This might explain the erratic results seen in virtio-win...
Perhaps we need to tee the socket data to a SNMP parser to check...
...but it might be quicker / easier to add the requisite features to the listener here... 8^d

2025-02-26 12:06 UTC, kostyanf14 commented
@benyamin-codez 

No, you are not correct. We analyze requests, and HLK always sends `ImmediateReboot` and nothing else.

2025-02-26 12:13 UTC, kostyanf14 commented
@benyamin-codez Also, if you open HLKX results where Flush test failed, you can see the error. Error looks like this: System reset was requested but system not rebooted.

2025-02-26 13:06 UTC, benyamin-codez commented
@kostyanf14 

Thanks for the prompt reply.

> No, you are not correct. We analyze requests, and HLK always sends ImmediateReboot and nothing else.

I saw the `socket.recvfrom(0)`, with the zero-sized buffer, and presumed you weren't looking...

> Also, if you open HLKX results where Flush test failed, you can see the error. Error looks like this:
> System reset was requested but system not rebooted.

Oh, ok. I was checking `Failed: Flush Test.zip` > `Test Run` > `WttEA.log` instead
I've only seen `0x80070002` (`ERROR_FILE_NOT_FOUND` errors) in the dozen or so I've checked.

I'll grab the Studio and have a peek... 8^d
Can you tell I'm trying to avoid installing the whole HLK...?  8^D  It seems like quite a beast...

2025-02-26 14:09 UTC, kostyanf14 commented
> I saw the `socket.recvfrom(0)`, with the zero-sized buffer, and presumed you weren't looking...

During development, we checked this data and found that it can be ignored. 

For example:
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1304 - viostor-Win2022x64
![image](https://github.com/user-attachments/assets/72d88c9e-5ee6-4404-8f0d-013e7b065921)
 
The error is not related to the storage driver but something with HLK.

2025-02-26 15:29 UTC, benyamin-codez commented
Yeah, that's what I see in the few I peeked into.
The actual test passes and then an error occurs during test cleanup.
Apparently it occurs whilst _"Initializing and formatting the disk"_...
So it doesn't ***appear*** to be related to this SNMP kit or reboots at all - at least in these cases.

Is it possible the disk is OFFLINE and so it cannot be initialised or formatted?
... If so, this is something we might need to address in the driver...
Is it perhaps something to do with the type of disk backing, i.e. COW or RAW?
This appears to be running (and failing) on non-bootable disks (as expected - except the failing part)...
I presume there's no AV or anything else interfering with anything in the boot block...

Quite annoying...! 8^(

2025-02-27 10:52 UTC, kostyanf14 commented
You can configure only the following options:
- IP 	IP Address of Remote PDU
- OID 	OID of Remote PDU outlet
- Outlet 	Port of Remote PDU outlet
- Community 	Community of Remote PDU (e.g. private)

All other configurations are done automatically by HLK (not AutoHCK)

2025-02-27 11:20 UTC, kostyanf14 commented
@benyamin-codez Let's continue in the discussion thread https://github.com/HCK-CI/AutoHCK/discussions/608. This is more complicated to find this PR and this creates extra mail noise for other people.