RFC: Bring up previous session
HCK-CI/AutoHCK pull request #487
Opened 2024-10-07 01:21 UTC by Jedoku

2024-10-10 12:38 UTC, akihikodaki commented
I'm not a fan of this idea. It brings significant complexity similar to `--dump`, which adds an alternative way to run tests.
Its use case is also unclear; I often repeatedly run tests using the command line history and I'm satisfied with it.

2024-10-19 08:07 UTC, akihikodaki requested changes

2024-10-19 08:07 UTC, akihikodaki commented on lib/project.rb
>      end
`@options.test.latest_session` is ignored.

2024-10-19 08:07 UTC, akihikodaki commented on lib/project.rb
> +    def add_latest_alias
Use "symlink" instead of introducing another word "alias".

2024-10-19 08:07 UTC, akihikodaki commented on lib/project.rb
> +    def init_session
This method should still be named `init_workspace`. It initialized more than `session.json`, which is part of workspace.

2024-12-03 05:35 UTC, akihikodaki requested changes

2024-12-03 05:35 UTC, akihikodaki commented on lib/project.rb
> +
Avoid an irrelevant change here.

2024-12-03 05:35 UTC, akihikodaki commented on lib/session.rb
> +      }.to_json
Use `T::Struct#serialize` here.

2024-12-03 05:35 UTC, akihikodaki commented on lib/models/session.rb
> +    end
This duplicates the definitions of attributes of `AutoHCK::Project`. Unify them.

2024-12-19 09:15 UTC, akihikodaki requested changes

2024-12-26 09:52 UTC, akihikodaki commented on lib/session.rb
> +      cli.common.share_on_host_path ||= session.common.share_on_host_path
Forget what I said about `clone` on the chat; it makes no difference at all.
I think the reason why it's looping when assigning `session.test` is that it restores the value of the `workspace_path` property, which was previously ignored. Please check what value it should have.

2024-12-26 09:54 UTC, akihikodaki commented on lib/session.rb
> +      }.to_json
We should use `Models::Session` because it's type-checked. If you directly create a hash, it will not be type-checked so is more error-prone.

2025-01-23 05:49 UTC, akihikodaki requested changes

2025-01-23 05:49 UTC, akihikodaki commented on lib/cli.rb
> +      prop :verbose, T.nilable(T::Boolean), default: false
```suggestion
      prop :verbose, T::Boolean, default: false
```

2025-01-23 05:49 UTC, akihikodaki commented on lib/cli.rb
> +      prop :debug, T::Boolean, default: false
Remove the default value assignments in `define_options` as you did for `CommonOptions`.

2025-01-23 05:49 UTC, akihikodaki commented on lib/session.rb
> +      cli.test.manual ||= true
Simpler:

```suggestion
      cli.test.manual = true
```

2025-01-23 05:49 UTC, akihikodaki commented on lib/models/session.rb
> +      const :common, T.nilable(AutoHCK::CLI::CommonOptions)
Why will `common` be nil?

2025-01-23 05:49 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +      create_zip_from_directory(zip_path, @driver_path) unless File.exist?(zip_path)
Can't you skip the whole `upload_driver_package` method?

2025-01-23 05:49 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +          run_clients_and_configure_setup(scope, group => true)
This change will create a snapshot for every group when not restored.

2025-01-23 05:49 UTC, akihikodaki commented on lib/project.rb
> +      @options.test.session ? session : create_session
`session` is a confusing name; it is a noun but has side effects.

2025-01-23 05:49 UTC, akihikodaki commented on lib/session.rb
> +      backup_cli = cli.clone
This `clone` can be removed by modifying `session` according to `cli` and then overwriting `cli`.

2025-01-23 05:49 UTC, akihikodaki commented on lib/models/session.rb
> +        }.to_json
Use `Session#serialize`.

2025-01-23 05:49 UTC, akihikodaki commented on lib/project.rb
> +    def create_session
It says `create_session` but it also creates the workspace directory, which is confusing.

2025-01-23 08:20 UTC, kostyanf14 commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +      end
I don't agree with filters in general. When we bring up the previous session all config commands were executed, so we should skip all of them.

2025-01-30 09:35 UTC, akihikodaki requested changes

2025-01-30 09:35 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +          run_clients_and_configure_setup(scope, create_snapshot: false, group => true)
Why did you change this?

2025-01-30 09:35 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +    def run # rubocop:disable Metrics/AbcSize
Refactor rather than disabling RuboCop.
In this case, I think you can remove the message "AutoHCK started in dump only mode"; it is obvious and we are not writing such a message for the auto run anyway.

2025-01-30 09:35 UTC, akihikodaki commented on lib/session.rb
> +# rubocop:disable Metrics/AbcSize,Lint/MissingCopEnableDirective
Why?

2025-01-30 09:35 UTC, akihikodaki commented on lib/session.rb
> +      session.common.workspace_path = workspace_path
This has a side effect of modifying `options`, which is obscure and should be avoided.

2025-01-30 09:35 UTC, akihikodaki commented on lib/cli.rb
> +      prop :id, T.nilable(Integer), default: 2
```suggestion
      prop :id, Integer, default: 2
```

2025-01-31 05:04 UTC, akihikodaki requested changes
The current implementation will leave an immature session if an error happens before clients get configured. Save the session after it is fully initialized (i.e., all clients are configured).

2025-01-31 10:01 UTC, Jedoku commented
> The current implementation will leave an immature session if an error happens before clients get configured. Save the session after it is fully initialized (i.e., all clients are configured).

But this is one of features, you can bring up VM`s for checking what's goin on and where it's crash

2025-01-31 10:48 UTC, kostyanf14 commented on lib/cli.rb
> +      prop :package_with_playlist, T.nilable(T::Boolean)
Don't see any reason to make boolean fields nilable. String or Array can be nilable because we have logic to check is field specified or not. But in the case of a boolean, we always check true or false.

2025-02-01 05:42 UTC, akihikodaki commented
> > The current implementation will leave an immature session if an error happens before clients get configured. Save the session after it is fully initialized (i.e., all clients are configured).
> 
> But this is one of features, you can bring up VM`s for checking what's goin on and where it's crash

The current code will make tests fail in an unpredictable manner instead of reproducing the past failure. It skips creating snapshots and configuration when restored so if some failure has happened in these operations, it will not reproduce the failure, but it will run the following tests with an immature configuration and pose different symptoms that are not useful to debug.

2025-02-01 10:15 UTC, Jedoku commented
It runs saved snapshots, and our VM's will be configured exactly as it was,
also on we can open studio and see what happens in previous session


On Sat, Feb 1, 2025 at 7:42 AM Akihiko Odaki ***@***.***>
wrote:

> The current implementation will leave an immature session if an error
> happens before clients get configured. Save the session after it is fully
> initialized (i.e., all clients are configured).
>
> But this is one of features, you can bring up VM`s for checking what's
> goin on and where it's crash
>
> The current code will make tests fail in an unpredictable manner instead
> of reproducing the past failure. It skips creating snapshots and
> configuration when restored so if some failure has happened in these
> operations, it will not reproduce the failure, but it will run the
> following tests with an immature configuration and pose different symptoms
> that are not useful to debug.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HCK-CI/AutoHCK/pull/487#issuecomment-2628790380>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANRORQZ7QAQGDXSBTNF6QMT2NRNGBAVCNFSM6AAAAABPO3NUC2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMRYG44TAMZYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-02-01 20:07 UTC, akihikodaki commented
> It runs saved snapshots, and our VM's will be configured exactly as it was, also on we can open studio and see what happens in previous session

At least the session should be saved at least after snapshots are created, and if the VMs died before configuration, we should configure them before continuing to run tests. 

The studio should have seen almost no activity at the early stage of execution before running tests; if it experienced a failure at the moment, it means the VM is so broken that it cannot boot or stay running for minutes. Such a scenario should be rare.

The easiest way to ensure the VMs are configured is simply to save the session after the configuration. It is sufficient to reproduce failures in tests.

2025-02-06 05:22 UTC, akihikodaki requested changes

2025-02-06 05:22 UTC, akihikodaki commented on lib/session.rb
> +  class Session
Make this module instead of class as instantiating it makes no sense.

2025-02-06 05:22 UTC, akihikodaki commented on lib/models/session.rb
> +end
What about letting `AutoHCK::CLI` inherit `T::Struct` so that we can remove this class?

2025-02-06 05:22 UTC, akihikodaki commented on lib/project.rb
>      end
I suggest merging this into `create_workspace`. Creating a workspace automatically makes it the latest so it makes sense to automatically update the symlink. The code in `init_workspace` will be more natural as you can write it to say "if being restored, restore the workspace; otherwise create a new one".

2025-02-06 05:22 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +          run_config_commands unless @run_opts[:restored]
Let's name the new option `configured` instead.
If it is named `restored`, this statement will mean: "if restored, the machine is already configured"; we already have such a logic in `HCKTest` so let the class contain the concern.
Theoretically, we can also instantiate `QemuMachine` without "restoring" in one session; whether restoration is happening or not does not matter for `QemuMachine`.

2025-02-06 05:22 UTC, akihikodaki commented on lib/project.rb
> +      @restored = @options.test.session
Avoid creating a new state by introducing a new instance variable if possible; you can define a `restored?` method instead.

2025-02-12 12:25 UTC, akihikodaki requested changes

2025-02-12 12:25 UTC, akihikodaki commented on lib/cli.rb
> +      restore_session if @test.latest_session || @test.session
Instead of passing self to `AutoHCK::Session.load` and letting it modify, let's pass the path to the session.
Such a method may be called from `bin/auto_hck` and return an instance of loaded `CLI`, which will replace the whole existing `CLI` instance.

So instead of having these lines in `session.rb`:
```rb
      cli.test = session.test
      cli.common = session.common
```

...add a line like the following in `auto_hck`:
```rb
cli = Session.load(session_path)
```

You don't have to list each attribute of `CLI` this way.

2025-03-03 04:25 UTC, akihikodaki requested changes

2025-03-03 04:25 UTC, akihikodaki commented on lib/cli.rb
> +    prop :install, T.nilable(InstallOptions), default: nil
Use `factory:` keyword argument documented in: https://sorbet.org/docs/tstruct

2025-03-03 04:25 UTC, akihikodaki commented on bin/auto_hck
> +                   elsif cli.test.session
Simpler:

```suggestion
                   else
```

2025-03-03 04:25 UTC, akihikodaki commented on bin/auto_hck
> +    cli = Session.load(session_path, cli) if session_path
Pass `cli.common.workspace_path` instead of `cli` to contain all code dealing with the original `cli` here (including the code deriving `session_path`).

2025-03-03 04:25 UTC, akihikodaki commented on lib/session.rb
> +end
Better to merge this into `AutoHCK::CLI` as its methods all deal with that class.

2025-03-03 09:19 UTC, akihikodaki requested changes

2025-03-03 09:19 UTC, akihikodaki commented on bin/auto_hck
> +    end
Simpler:

```suggestion
    session_path = cli.test.latest_session ? "#{Config.read['workspace_path']}/latest" : cli.test.session
    cli = Session.load(session_path, cli) if session_path
```

2025-03-19 09:20 UTC, akihikodaki requested changes
See the unresolved comments.

2025-03-27 08:46 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +          run_clients_and_configure_setup(scope, create_snapshot: false, group => true)
My question is not about session restoration, but about the normal case that does not involve session restoration. This change will affect all scenarios since it does not check `project.restored?`; is that OK?

2025-03-27 08:50 UTC, akihikodaki requested changes

2025-03-27 08:50 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +        unless run_opts[:configured]
```suggestion
        unless @run_opts[:configured]
```

2025-03-27 08:50 UTC, akihikodaki commented on lib/cli.rb
> +    attr_accessor :common, :test
I don't think they are necessary.

2025-03-27 08:50 UTC, akihikodaki commented on lib/session.rb
> +    prop :mode, T.nilable(String), default: nil
At https://github.com/HCK-CI/AutoHCK/pull/487#discussion_r1981046821, I suggested adding a property for `CLI` instead of properties that `CLI` has.

2025-04-03 05:45 UTC, akihikodaki requested changes

2025-04-03 05:45 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +          @run_opts[:configured] = true
The changes in `qemu_machine.rb` break the scenario where the `run` method is called multiple times without `configured` specified.

2025-04-03 05:45 UTC, akihikodaki commented on lib/cli.rb
> +    attr_reader :common, :install, :test, :mode
I don't think these are necessary.

2025-04-03 05:45 UTC, akihikodaki commented on lib/session.rb
> +      logger.info("Session saved to #{workspace_path}/session.json")
It's not saving `Session` but saving `CLI`.

2025-04-03 06:15 UTC, Jedoku commented on lib/session.rb
> +      logger.info("Session saved to #{workspace_path}/session.json")
Indeed

2025-04-07 10:18 UTC, kostyanf14 commented on lib/session.rb
> +      logger.info("Session saved to #{workspace_path}/session.json")
```
    def self.save(workspace_path, logger)
      File.write("#{workspace_path}/session.json", self.to_json)
```

2025-04-10 08:56 UTC, akihikodaki requested changes

2025-04-10 08:56 UTC, akihikodaki commented on lib/session.rb
> +    end
Make this a class method as it creates a new instance.

2025-04-10 08:56 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +      @configured ||= @run_opts[:configured]
Do not ignore `@run_opts[:configured]` when the caller set it to `false`.

2025-04-29 09:41 UTC, akihikodaki requested changes

2025-04-29 09:41 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +      @configured = @run_opts[:configured] if [true, false].include?(@run_opts[:configured])
To make this simpler and torelate other truthy and falsy values:

```suggestion
      @configured = @run_opts[:configured] if @run_opts.key?(:configured)
```

2025-04-29 09:41 UTC, akihikodaki commented on lib/engines/hcktest/tests.rb
> -
This changr is irrelevant.

2025-05-04 07:12 UTC, akihikodaki requested changes

2025-05-04 07:12 UTC, akihikodaki commented on lib/project.rb
> +    end
This method is too trivial. I would rather fix the Rubocop warning with `initialize` by removing `@id`.

2025-05-26 03:26 UTC, akihikodaki requested changes
Please look at unresolved comments:
- https://github.com/HCK-CI/AutoHCK/pull/487#discussion_r2015972343
- https://github.com/HCK-CI/AutoHCK/pull/487#discussion_r2026245429
- https://github.com/HCK-CI/AutoHCK/pull/487#discussion_r2036861966

2025-05-28 03:53 UTC, akihikodaki requested changes

2025-05-28 03:53 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +          run_clients tmp_scope, keep_alive: true, **opts, **init_vm_options
`**init_vm_options` is already applied by `run_tests_without_config`.

2025-05-28 03:53 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> -
This change is irrelevant.

2025-05-28 03:53 UTC, akihikodaki commented on lib/session.rb
> +      T.must(session.cli.common).workspace_path = workspace_path
`T.must` is no longer necessary.

2025-05-29 04:14 UTC, akihikodaki requested changes

2025-05-29 05:06 UTC, akihikodaki requested changes
Two of the last comments are not addressed.

2025-05-29 05:23 UTC, Jedoku commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
I actually don't clearly remember it but, i think it was some error relatet to target creation back then
Anyway it's works without it now

2025-05-29 05:26 UTC, akihikodaki commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
Rescue an error only when restored. Checking `File.directory?(session_path)` results in a duplicate file operation and a "time-of-check to time-of-use" race condition, which is why I suggest rescuing one.

2025-05-29 05:31 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
The new version removed the condition, but `@tests.verify_target` is still there.

2025-05-29 05:32 UTC, akihikodaki submitted a review, later dismissed
I replied to the comments so please check them out.

2025-05-29 05:54 UTC, Jedoku commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
It actually will be rised by OpenJsonError if it's does't exist, I dont want to rescue it's doesn't make sense for me we can have a little double operation or you can sugget another one

2025-05-29 06:07 UTC, Jedoku commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
Look, we cant catch Errno::ENOENT error here Cause its already catched by Json helper and our rescue will be ignored
So we can remove this rising of error and will see that session.JSON does not exist ant it will be unclear that workspace_path doesn't exist

2025-05-29 06:14 UTC, Jedoku commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
```
I, [2025-05-29T09:11:23.184397 #1941716]  INFO -- CmdRun PID:1943108: Command finished with code 0
F, [2025-05-29T09:11:23.184889 #1941716] FATAL -- : (NoMethodError) undefined method `[]' for nil
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/engines/hcktest/tests.rb:61:in `update_tests'
   -- /home/jedoku/HCK/repos/AutoHCK.git/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.12020/lib/types/private/methods/call_validation.rb:282:in `bind_call'
   -- /home/jedoku/HCK/repos/AutoHCK.git/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.12020/lib/types/private/methods/call_validation.rb:282:in `validate_call'
   -- /home/jedoku/HCK/repos/AutoHCK.git/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.12020/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/engines/hcktest/hcktest.rb:253:in `prepare_tests'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/engines/hcktest/hcktest.rb:281:in `block in run_tests_without_config'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:29:in `block (2 levels) in open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:28:in `handle_interrupt'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:28:in `block in open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:27:in `handle_interrupt'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:27:in `open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/engines/hcktest/hcktest.rb:279:in `run_tests_without_config'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/engines/hcktest/hcktest.rb:271:in `block in auto_run'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:29:in `block (2 levels) in open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:28:in `handle_interrupt'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:28:in `block in open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:27:in `handle_interrupt'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:27:in `open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/engines/hcktest/hcktest.rb:267:in `auto_run'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/engines/hcktest/hcktest.rb:329:in `run'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/project.rb:48:in `run'
   -- bin/auto_hck:30:in `block (2 levels) in <module:AutoHCK>'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:29:in `block (2 levels) in open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:28:in `handle_interrupt'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:28:in `block in open'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:27:in `handle_interrupt'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auxiliary/resource_scope.rb:27:in `open'
   -- bin/auto_hck:27:in `block in <module:AutoHCK>'
   -- /home/jedoku/HCK/repos/AutoHCK.git/lib/auto_hck.rb:14:in `run'
   -- bin/auto_hck:9:in `<module:AutoHCK>'
   -- bin/auto_hck:8:in `<main>'
D, [2025-05-29T09:11:23.185073 #1941716] DEBUG -- : Closing AutoHCK project
```

2025-05-29 06:14 UTC, Jedoku commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
That's why it was there

2025-05-29 06:15 UTC, Jedoku commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
`I, [2025-05-29T09:10:41.233651 #1941716]  INFO -- : HLK test target is not defined, allow in manual mode
I, [2025-05-29T09:10:41.234026 #1941716]  INFO -- : Exiting HLKClient CL1
I, [2025-05-29T09:10:41.234185 #1941716]  INFO -- : Sending powerdown signal to QemuMachine0002_CL01 via QMP
I, [2025-05-29T09:11:08.072050 #1941716]  INFO -- CmdRun PID:1942171: Command finished with code 0`

2025-05-29 06:29 UTC, akihikodaki commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
By the way, do we really need to check if it was `Errno::ENOENT`? I guess you can always tell the user that loading a session failed, whatever the error was.

2025-05-29 06:34 UTC, Jedoku commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
but its only related do json file, its unclear that whole workspace path does not exist

2025-05-29 06:38 UTC, akihikodaki commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
I think the problem here is that `AutoHCK::OpenJsonError` is redundant. It will be clear if we stop raising that exception for `Errno::ENOENT`.

2025-05-29 06:45 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
The log indicates the underlying problem is that `HCKClient#add_target_to_project` is not called because 
`configure_and_synchronize_clients` is skipped. Letting `configure_and_synchronize_clients` call `HCKClient#add_target_to_project` would be a proper fix.

2025-05-29 06:45 UTC, Jedoku commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
>  If the whole workspace path doesn't exist, the user specified a wrong path. If only the JSON file is missing, the user specified a path to a wrong directory. Either way, the user needs to check if they typed the correct path.

That's how it works right now

2025-05-29 06:48 UTC, akihikodaki commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
> > If the whole workspace path doesn't exist, the user specified a wrong path. If only the JSON file is missing, the user specified a path to a wrong directory. Either way, the user needs to check if they typed the correct path.
> 
> That's how it works right now

Yes, but `File.directory?(session_path)` is unnecessary.

2025-05-29 06:54 UTC, Jedoku commented on lib/project.rb
> +      raise AutoHCKError, 'Workspace path does not exist could not load session' unless File.directory?(@workspace_path)
done

2025-05-29 07:06 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
Right. We need another method to call `search_target` instead.

2025-05-29 07:09 UTC, Jedoku commented on lib/engines/hcktest/hcktest.rb
> +      @tests.verify_target if @project.restored?
What's wrong with verify_target?

2026-05-26 07:21 UTC, closed without merging

2026-05-26 07:21 UTC, kostyanf14 commented
Replaced https://github.com/HCK-CI/AutoHCK/pull/977