Skip selected as a boot device driver
HCK-CI/AutoHCK pull request #506
Opened 2024-10-24 18:31 UTC by Jedoku

2024-10-25 04:00 UTC, akihikodaki requested changes

2024-10-25 04:00 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +      return false unless @project.options.test.svvp
What happens if `@project.options.test.svvp && driver.device == @project.options.test.boot_device`?

2024-10-25 06:42 UTC, kostyanf14 reviewed
@akihikodaki 

Currently, we have broken QEMU CLI for SVVP, not sure this is a bug or not, because we add the same device 2 times. The old problem was during driver installation, pnputil fail and auto_hck fail

2024-10-26 03:56 UTC, akihikodaki commented
> Currently, we have broken QEMU CLI for SVVP, not sure this is a bug or not, because we add the same device 2 times. The old problem was during driver installation, pnputil fail and auto_hck fail

In that case, let's remove the statement `return false unless @project.options.test.svvp`. It does not seem to be the correct way to determine whether the driver is already installed for SVVP. We need to figure out that later.

2024-10-31 07:10 UTC, akihikodaki requested changes

2024-10-31 07:10 UTC, akihikodaki commented on lib/engines/hcktest/hcktest.rb
> +    end
Let's merge this method into `find_drivers`; this method is now just one statement.

2024-11-05 07:35 UTC, akihikodaki approved these changes

2024-11-05 07:51 UTC, kostyanf14 approved these changes

2024-11-05 07:51 UTC, merged