QemuHCK: Fix missing iommu_device_param on device
HCK-CI/AutoHCK pull request #516
Opened 2024-11-06 12:50 UTC by kostyanf14

2024-11-06 13:22 UTC, YanVugenfirer approved these changes

2024-11-06 13:28 UTC, YanVugenfirer approved these changes

2024-11-07 04:48 UTC, akihikodaki requested changes

2024-11-07 04:48 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +      @device_infos.map(&:iommu_device_param).flatten.compact
Use `flat_map`.

2024-11-07 04:49 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +      @device_infos.map(&:iommu_device_param).flatten.compact
No, `iommu_device_param` is not an Array but just a mere String so we can just omit `flatten`.

2024-11-07 08:55 UTC, akihikodaki requested changes

2024-11-07 08:55 UTC, akihikodaki commented on lib/setupmanagers/qemuhck/qemu_machine.rb
> +      @device_infos.map(&:iommu_device_param).compact
Use `filter_map` to make this even shorter.

2024-11-07 09:19 UTC, akihikodaki approved these changes

2024-11-07 10:11 UTC, merged